---
- name: install docker
  yum:
    name: docker
    state: latest

- name: register image build
  command: docker images
  register: result

- name: build image
  command: docker build -t mmodal/anagram ./ans-mmodal/files/
  when: result != ""
  
- name: run anagram.py
  command: docker run mmodal/anagram
  environment:
    STRING_ONE: "{{str_one}}"
    STRING_TWO: "{{str_two}}"
  register: anagram

- debug:
  msg: anagram