---
- block:
    - name: register docker is installed
      package:
        name: docker
        state: latest
      check_mode: true
      register: check_installed

    - name: install docker
      yum:
        name: docker
        state: latest
      when: check_installed.changed

    - name: register image build
      command: docker images mmodal/anagram
      register: result

    - name: build image
      command: docker build -t mmodal/anagram /opt/ans-mmodal/files/
      when: result.stdout_lines|length < 2
    
    - name: run anagram.py
      command: docker run -e STRING_ONE="{{str_one}}" -e STRING_TWO="{{str_two}}" mmodal/anagram
      register: anagram
    
    - debug:
        msg: "{{anagram.stdout_lines}}"
  when:
    - str_one is defined
    - str_two is defined
    
- debug:
    msg: "str_one and str_two have to be present"
  when: str_one is not defined or str_two is not defined
