---
- name: install docker
  yum:
    name: docker
    state: latest
- name: build image
  command: docker build -t mmodal/anagram
- name: run anagram.py
  command: docker run mmodal/anagram -e STRING_ONE={{str_one}} -e STRING_TWO={{str_two}}
